apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-backup
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mysqlbackup
            image: mysql:5.6
            args:
            - /bin/sh
            - -c
            - mysqldump -hmysql.default -uroot -ppassword --all-databases > "/var/tmp/mysql_backup.$(date %F_%R).sql"
            volumeMounts:
              - name: dbbackup
                mountPath: /var/tmp
          volumes:
            - name: dbbackup
              nfs:
                path: /var/nfs/data
                server: 192.168.29.182
          restartPolicy: OnFailure