Always : means that the container will be restarted even if it exited with a zero exit code (i.e. successfully). This is useful when you don't care why the container exited, you just want to make sure that it is always running (e.g. a web server). This is the default.

OnFailure : means that the container will only be restarted if it exited with a non-zero exit code (i.e. something went wrong). This is useful when you want accomplish a certain task with the pod, and ensure that it completes successfully - if it doesn't it will be restarted until it does.

Never :  means that the container will not be restarted regardless of why it exited.

apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  template:
    spec:
      containers:
      - name: mysqlbackup
        image: mysql:5.6
        args:
        - /bin/sh
        - -c
        - mysqldump -hmysql.default -uroot -ppassword --all-databases > /var/tmp/mysql_backup.sql
        volumeMounts:
          - name: dbbackup
            mountPath: /var/tmp
      volumes:
        - name: dbbackup
          nfs:
            path: /var/nfs/data
            server: 192.168.29.182
      restartPolicy: OnFailure