apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: sample-container
spec:
  nodeSelector:
    disktype: ssd
  containers:
    - name: first-container
      image: nginx


#kubectl label node nodename disktype=ssd
#kubectl get nodes --show-labels
#kubectl get nodes -l disktype=ssd