apiVersion: v1
kind: Pod
metadata:
  name: basic-nginx
  labels:
    nginx: basictest
spec:
  nodeSelector:
    app: sudhams
  containers:
  - name: nginx-c1
    image: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  revisionHistoryLimit: 5
  strategy:
    type: Recreate
  replicas: 3
  selector:
    matchLabels:
      app: temp-nginx
  template:
    metadata:
      labels:
        app: temp-nginx
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: nginx
                operator: In
                values:
                - basictest
            topologyKey: kubernetes.io/hostname
      containers:
      - name: nginx
        image: nginx #1.16.1
        ports:
        - containerPort: 80