kubectl taint nodes node1 key=value:NoSchedule
kubectl taint nodes node1 key=value:NoExecute
kubectl taint nodes node1 key=value:PreferNoSchedule


Remove taint to the nodes:
#kubectl taint nodes node1 key:NoSchedule-

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  tolerations:
  - key: "key" #node-role.kubernetes.io/master
    operator: "Exists"
    effect: "NoSchedule"

#kubectl taint nodes es-node elasticsearch=false:NoExecute

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  tolerations:
  - key: elasticsearch
    operator: Equal
    value: false
    effect: NoExecute