#Covert the password which you want to set to root user using base64
#echo -n "test123" | base64
#echo "dGVzdDEyMw==" | base64 -d
#take the output and update the secret file
apiVersion: v1
kind: Secret
metadata:
  name: mysqldb-secret
data:
  mysql_root_passwd: dGVzdDEyMw==

---
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        args:
          - "--ignore-db-dir=lost+found"
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysqldb-secret
                key: mysql_root_passwd
          - name: MYSQL_ROOT_HOST
            value: "%"
          - name: MYSQL_ROOT_USER
            valueFrom:
              configMapKeyRef:
                name: root-user
                key: ROOT_USER
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        hostPath:
          path: /mysql_data
          type: DirectoryOrCreate


#Now check the mysql connection with help of creating temporary container to
#check the mysql access
#kubectl exec -it podname -- mysql -h mysql -pXXXXX
# kubectl exec -it mysql-75d9c6f849-9k4h4 -- mysql -h10.244.1.226 -uroot -p
